name: hrm.hrm_act_v1@HierarchicalReasoningModel_ACTV1
loss:
  name: losses@MinLossACTLossHead
  loss_type: stablemax_cross_entropy

input_seq_len: 24  # 2x2 cube state = 24 sticker values

halt_exploration_prob: 0.1
halt_max_steps: 16

H_cycles: 8
L_cycles: 8

H_layers: 4
L_layers: 4

hidden_size: 128
num_heads: 2
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
