# 2x2x2 Rubik's Cube Heuristic training config (regression task)

defaults:
  - arch: hrm_v1_regression
  - _self_

hydra:
  output_subdir: null

# Data path
data_path: data/cube-2-by-2-heuristic
# Naming (stable paths for checkpoints)
project_name: "Cube-2-by-2-heuristic ACT-torch"
run_name: "HierarchicalReasoningModel_ACTV1 h128-nh4 mse"
resume_checkpoint: "checkpoints/Cube-2-by-2-heuristic ACT-torch/HierarchicalReasoningModel_ACTV1 h128-nh4 mse/step_48750"

# Hyperparams - Training
global_batch_size: 256

epochs: 64
eval_interval: 4
checkpoint_every_eval: True

lr: 5e-5
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 3e-3
